sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false

node_js:
  - '10'
  - '8'
install:
  - if [[ "${TRAVIS_TAG}" == "" ]]; then npm install; fi
script:
  - if [[ "${TRAVIS_TAG}" == "" ]]; then npm run lint; fi
#  - if [[ "${TRAVIS_TAG}" == "" ]]; then npm run ava; fi
after_success:
  - if [[ "${TRAVIS_BRANCH}" == "master"  ]] && [[ "${TRAVIS_TAG}" == "" ]]; then npm run travis-deploy-once "npm run semantic-release"; fi
jobs:
  include:
    - stage: docker release
      node_js: '8'
      if: tag IS present
      script:
        - docker build -t allovince/avnpc.front .
        - docker tag allovince/avnpc.front allovince/avnpc.front:$TRAVIS_TAG
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push allovince/avnpc.front:latest;
        - docker push allovince/avnpc.front:$TRAVIS_TAG;
